//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/movePlayer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MovePlayer: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MovePlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""movePlayer"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""6c5e4dd8-6575-404a-aa38-421ec007b2c0"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""cea5b311-2b97-481b-81bc-286e402b2e90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Recoger"",
                    ""type"": ""Button"",
                    ""id"": ""1ee987d4-e34e-42dd-8cbb-0d4fc3688362"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaccion"",
                    ""type"": ""Button"",
                    ""id"": ""098627a5-98d6-4678-b955-e4a4d4d98541"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CanvasActive"",
                    ""type"": ""Button"",
                    ""id"": ""38ba0f2c-d4c1-4ee7-a2ef-69a7046bad64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe"",
                    ""type"": ""Button"",
                    ""id"": ""2f8718c4-5f84-4314-b2bd-894fc4996234"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cocina"",
                    ""type"": ""Button"",
                    ""id"": ""1480f919-5821-43ba-bd5f-8a027398d4d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""51a63cc4-0bca-4230-87a9-19c227dbc3da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5ef9cfa8-3879-4f80-96a6-f83cbf2cc43e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d030512a-1d8d-4a3a-a45d-0b9cb26519c6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4d6a3dbb-3c72-4e0c-9b93-b944019f0ed7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcccb1ba-2182-42f3-90fb-3feaee5c4ed2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""bb75e24b-3c4c-4f99-b780-c0c4318faa13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4a0b2c1d-91ae-43fb-8ff0-ed268f0bea99"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a47287de-899e-4b06-9bea-81cdb449eeb0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f22d1451-1b43-456a-953f-d8bb19640d3d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d8be9b13-9417-4d8a-9b5c-6fdd2cd1eb81"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9dfbd8e7-af9b-4fcf-a65f-26c89acc3a1a"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recoger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0404f366-ffca-47df-8dd8-797f59ac046a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recoger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07dea48d-f351-44d8-97ab-c4000973032a"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaccion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c79a0329-a379-4faf-b8cd-dbff2890482e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaccion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e6930b8-53d2-4257-bbbf-fb0f4d885d35"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CanvasActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da7cacce-b415-45a4-82e8-7d0f34d6e73b"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CanvasActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa4c019b-9b6f-4c40-880f-7a36eac060fb"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd9c07e-38d8-4404-86a4-fa7d034fb6eb"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49d549c9-8845-4100-96c2-30dd846d8e6a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0380946c-4ea9-4693-a870-a95fd0980ee3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18636489-110f-42cb-be0a-02077ad21521"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7097cf9a-0357-4281-868b-e4e930f4d75e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""4c171933-0393-467e-b066-887470d52925"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""acf7ff9f-a09a-4416-854c-0d60f09f6693"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Recoger"",
                    ""type"": ""Button"",
                    ""id"": ""26e7752c-881e-4e0d-9d82-7b733ac5a3f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaccion"",
                    ""type"": ""Button"",
                    ""id"": ""77c44835-f2e6-4de6-aae3-4bc8bb374e0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CanvasActive"",
                    ""type"": ""Button"",
                    ""id"": ""59b5dac4-ab2c-466a-b5c9-d0a23d3a7784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe"",
                    ""type"": ""Button"",
                    ""id"": ""4aa87dc2-726b-485d-ba9a-aa4f73e0eb4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cocina"",
                    ""type"": ""Button"",
                    ""id"": ""c129d383-89f1-46ca-b596-9c67b691fbf6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Joystick"",
                    ""id"": ""f1818557-80b9-4aee-9888-df0855399888"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb06961f-3e7c-46d3-9dd5-ee43cfc33273"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b7e26752-01b8-4d25-ad05-0f754bf6b926"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bc2deec9-3cca-4bf5-b509-b0fd31c85b61"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97996a7d-168b-4f2e-880b-0ab6656c7196"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0894e309-3920-4f34-8d57-9ea6d87caa31"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recoger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd960122-9645-4038-90f3-d4c4c30a8668"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaccion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff7b3f8e-5385-43b1-9734-cff66861f19b"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CanvasActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37b64611-f21d-4b55-a85b-826fb47f0692"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b186ef8e-ba75-46ab-b49f-4839db28a206"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""256b4c57-aaad-4acb-95c8-a34433f3c18d"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a80ad820-c299-426b-9db4-c06381fce433"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05b595cc-c6a2-468b-8adb-77cafe6cbe10"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Cocina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Teclado"",
            ""bindingGroup"": ""Teclado"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mando"",
            ""bindingGroup"": ""Mando"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Recoger = m_Player.FindAction("Recoger", throwIfNotFound: true);
        m_Player_Interaccion = m_Player.FindAction("Interaccion", throwIfNotFound: true);
        m_Player_CanvasActive = m_Player.FindAction("CanvasActive", throwIfNotFound: true);
        m_Player_Golpe = m_Player.FindAction("Golpe", throwIfNotFound: true);
        m_Player_Cocina = m_Player.FindAction("Cocina", throwIfNotFound: true);
        // Player2
        m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
        m_Player2_Move = m_Player2.FindAction("Move", throwIfNotFound: true);
        m_Player2_Recoger = m_Player2.FindAction("Recoger", throwIfNotFound: true);
        m_Player2_Interaccion = m_Player2.FindAction("Interaccion", throwIfNotFound: true);
        m_Player2_CanvasActive = m_Player2.FindAction("CanvasActive", throwIfNotFound: true);
        m_Player2_Golpe = m_Player2.FindAction("Golpe", throwIfNotFound: true);
        m_Player2_Cocina = m_Player2.FindAction("Cocina", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Recoger;
    private readonly InputAction m_Player_Interaccion;
    private readonly InputAction m_Player_CanvasActive;
    private readonly InputAction m_Player_Golpe;
    private readonly InputAction m_Player_Cocina;
    public struct PlayerActions
    {
        private @MovePlayer m_Wrapper;
        public PlayerActions(@MovePlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Recoger => m_Wrapper.m_Player_Recoger;
        public InputAction @Interaccion => m_Wrapper.m_Player_Interaccion;
        public InputAction @CanvasActive => m_Wrapper.m_Player_CanvasActive;
        public InputAction @Golpe => m_Wrapper.m_Player_Golpe;
        public InputAction @Cocina => m_Wrapper.m_Player_Cocina;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Recoger.started += instance.OnRecoger;
            @Recoger.performed += instance.OnRecoger;
            @Recoger.canceled += instance.OnRecoger;
            @Interaccion.started += instance.OnInteraccion;
            @Interaccion.performed += instance.OnInteraccion;
            @Interaccion.canceled += instance.OnInteraccion;
            @CanvasActive.started += instance.OnCanvasActive;
            @CanvasActive.performed += instance.OnCanvasActive;
            @CanvasActive.canceled += instance.OnCanvasActive;
            @Golpe.started += instance.OnGolpe;
            @Golpe.performed += instance.OnGolpe;
            @Golpe.canceled += instance.OnGolpe;
            @Cocina.started += instance.OnCocina;
            @Cocina.performed += instance.OnCocina;
            @Cocina.canceled += instance.OnCocina;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Recoger.started -= instance.OnRecoger;
            @Recoger.performed -= instance.OnRecoger;
            @Recoger.canceled -= instance.OnRecoger;
            @Interaccion.started -= instance.OnInteraccion;
            @Interaccion.performed -= instance.OnInteraccion;
            @Interaccion.canceled -= instance.OnInteraccion;
            @CanvasActive.started -= instance.OnCanvasActive;
            @CanvasActive.performed -= instance.OnCanvasActive;
            @CanvasActive.canceled -= instance.OnCanvasActive;
            @Golpe.started -= instance.OnGolpe;
            @Golpe.performed -= instance.OnGolpe;
            @Golpe.canceled -= instance.OnGolpe;
            @Cocina.started -= instance.OnCocina;
            @Cocina.performed -= instance.OnCocina;
            @Cocina.canceled -= instance.OnCocina;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Player2
    private readonly InputActionMap m_Player2;
    private List<IPlayer2Actions> m_Player2ActionsCallbackInterfaces = new List<IPlayer2Actions>();
    private readonly InputAction m_Player2_Move;
    private readonly InputAction m_Player2_Recoger;
    private readonly InputAction m_Player2_Interaccion;
    private readonly InputAction m_Player2_CanvasActive;
    private readonly InputAction m_Player2_Golpe;
    private readonly InputAction m_Player2_Cocina;
    public struct Player2Actions
    {
        private @MovePlayer m_Wrapper;
        public Player2Actions(@MovePlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player2_Move;
        public InputAction @Recoger => m_Wrapper.m_Player2_Recoger;
        public InputAction @Interaccion => m_Wrapper.m_Player2_Interaccion;
        public InputAction @CanvasActive => m_Wrapper.m_Player2_CanvasActive;
        public InputAction @Golpe => m_Wrapper.m_Player2_Golpe;
        public InputAction @Cocina => m_Wrapper.m_Player2_Cocina;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player2ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Recoger.started += instance.OnRecoger;
            @Recoger.performed += instance.OnRecoger;
            @Recoger.canceled += instance.OnRecoger;
            @Interaccion.started += instance.OnInteraccion;
            @Interaccion.performed += instance.OnInteraccion;
            @Interaccion.canceled += instance.OnInteraccion;
            @CanvasActive.started += instance.OnCanvasActive;
            @CanvasActive.performed += instance.OnCanvasActive;
            @CanvasActive.canceled += instance.OnCanvasActive;
            @Golpe.started += instance.OnGolpe;
            @Golpe.performed += instance.OnGolpe;
            @Golpe.canceled += instance.OnGolpe;
            @Cocina.started += instance.OnCocina;
            @Cocina.performed += instance.OnCocina;
            @Cocina.canceled += instance.OnCocina;
        }

        private void UnregisterCallbacks(IPlayer2Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Recoger.started -= instance.OnRecoger;
            @Recoger.performed -= instance.OnRecoger;
            @Recoger.canceled -= instance.OnRecoger;
            @Interaccion.started -= instance.OnInteraccion;
            @Interaccion.performed -= instance.OnInteraccion;
            @Interaccion.canceled -= instance.OnInteraccion;
            @CanvasActive.started -= instance.OnCanvasActive;
            @CanvasActive.performed -= instance.OnCanvasActive;
            @CanvasActive.canceled -= instance.OnCanvasActive;
            @Golpe.started -= instance.OnGolpe;
            @Golpe.performed -= instance.OnGolpe;
            @Golpe.canceled -= instance.OnGolpe;
            @Cocina.started -= instance.OnCocina;
            @Cocina.performed -= instance.OnCocina;
            @Cocina.canceled -= instance.OnCocina;
        }

        public void RemoveCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);
    private int m_TecladoSchemeIndex = -1;
    public InputControlScheme TecladoScheme
    {
        get
        {
            if (m_TecladoSchemeIndex == -1) m_TecladoSchemeIndex = asset.FindControlSchemeIndex("Teclado");
            return asset.controlSchemes[m_TecladoSchemeIndex];
        }
    }
    private int m_MandoSchemeIndex = -1;
    public InputControlScheme MandoScheme
    {
        get
        {
            if (m_MandoSchemeIndex == -1) m_MandoSchemeIndex = asset.FindControlSchemeIndex("Mando");
            return asset.controlSchemes[m_MandoSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRecoger(InputAction.CallbackContext context);
        void OnInteraccion(InputAction.CallbackContext context);
        void OnCanvasActive(InputAction.CallbackContext context);
        void OnGolpe(InputAction.CallbackContext context);
        void OnCocina(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRecoger(InputAction.CallbackContext context);
        void OnInteraccion(InputAction.CallbackContext context);
        void OnCanvasActive(InputAction.CallbackContext context);
        void OnGolpe(InputAction.CallbackContext context);
        void OnCocina(InputAction.CallbackContext context);
    }
}
